# Generated by Django 3.2.15 on 2022-09-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=100, null=True, verbose_name='Токен, привязанный к пользователю'),
        ),
    ]
