# Generated by Django 3.2.15 on 2022-09-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hex_color',
            new_name='color',
        ),
    ]
